spring:
  application.name: spring-demo
  profiles.active: dev
server.port: 9000

bar.menu.address: http://localhost:9001
pizza.menu.address: http://localhost:9001
storage.address: http://localhost:9001
ledger.address: http://localhost:9001